### PR TITLE
Add Bootstrap theme

### PR DESCRIPTION
**Pull request by NaveenDA**
28755574-934f23c0-757b-11e7-9663-6de1a72ada54

### CODE REVIEW

**Comment by Dygear** [comment]
I love you.

**Comment by mymedia2** [comment]
Is there somewhere a source code of this minified blob?

**Comment by NaveenDA** [comment]
Sorry, I don't get it. If you ask theme source code then here it is https://github.com/phpLiteAdmin/pla/blob/master/themes/Bootstrap/phpliteadmin.css

**Comment by mymedia2** [comment]
phpLiteAdmin is licensed under GPL 3. In accordance with section 1, the "source code" means the preferred form for making modifications to the program. This very long one-line CSS doesn't look like the suitable form for making modifications by human. It consists of pieces of Bootstrap and normalize.css plus some your own style rules without sources.

**Comment by NaveenDA** [comment]
Yes I know, I am using bootstrap.scss. As of now, I could not find any scss build tools used in PLA, that's why I upload direct output. FYI: If you want those scss files I will be sent to you.

**Comment by mymedia2** [comment]
@NaveenDA, thank you for offering! You can post the source here or send it to my email <guriev-ns@ya.ru>.

May I use it for the [phpliteadmin][1] package in Debian? We have [DFSG][2], and so the source code should meet these criteria.

 [1]: https://tracker.debian.org/pkg/phpliteadmin
 [2]: https://www.debian.org/social_contract#guidelines

**Comment by crazy4chrissi** [comment]
I would appreciate if we could upload the scss file into our git (additionally to the css file). Just in case somebody else would like to modify the theme in the future. Probably we would not include it in the themes zip-package, though (which, by the way, I need to update).

**Comment by crazy4chrissi** [comment]
Thanks @NaveenDA !
Is this everything you need @mymedia2 ?

**Comment by NaveenDA** [comment]
Hi @crazy4chrissi, @mymedia2 asked  “May I use it under GPL terms and put
it into the phpliteadmin Debian package?”, but I don't know about license details, can you answer this?

**Comment by mymedia2** [comment]
@crazy4chrissi, @NaveenDA, thank you for the published source code! I think this little issue is now resolved.

**Pull request merged**
